# Generated by Django 5.2 on 2025-04-17 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("book", "0002_alter_author_options_alter_book_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("DNI", models.CharField(max_length=16, verbose_name="DNI")),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Apellido"),
                ),
            ],
            options={
                "verbose_name": "Estudiante",
                "verbose_name_plural": "Estudiantes",
            },
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=70, verbose_name="Titulo")),
                ("date", models.DateField(blank=True, null=True, verbose_name="Fecha")),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to="book.book",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to="loan.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prestamo",
                "verbose_name_plural": "Prestamos",
            },
        ),
        migrations.CreateModel(
            name="BookReturn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="Fecha")),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booksreturn",
                        to="loan.loan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Regreso de libro",
                "verbose_name_plural": "Regreso de libros",
            },
        ),
    ]
