# Generated by Django 5.2 on 2025-04-17 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0002_alter_author_options_alter_book_options_and_more"),
        ("loan", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookreturn",
            options={
                "verbose_name": "Devolución",
                "verbose_name_plural": "Devoluciones",
            },
        ),
        migrations.RemoveField(
            model_name="loan",
            name="title",
        ),
        migrations.AddField(
            model_name="loan",
            name="description",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Descripción"
            ),
        ),
        migrations.AlterField(
            model_name="bookreturn",
            name="date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha devolución"
            ),
        ),
        migrations.AlterField(
            model_name="bookreturn",
            name="loan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="loan.loan",
                verbose_name="Prestamo",
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="book.book",
                verbose_name="Libro",
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha prestamo"
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="loan.student",
                verbose_name="Estudiante",
            ),
        ),
    ]
