# Generated by Django 5.2 on 2025-04-17 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={"verbose_name": "Autor", "verbose_name_plural": "Autores"},
        ),
        migrations.AlterModelOptions(
            name="book",
            options={"verbose_name": "Libro", "verbose_name_plural": "Libros"},
        ),
        migrations.AlterModelOptions(
            name="editorial",
            options={"verbose_name": "Editorial", "verbose_name_plural": "Editoriales"},
        ),
        migrations.AddField(
            model_name="book",
            name="cover",
            field=models.ImageField(
                blank=True, null=True, upload_to="book_stock", verbose_name="Portada"
            ),
        ),
        migrations.AlterField(
            model_name="author",
            name="country",
            field=models.CharField(max_length=30, verbose_name="País"),
        ),
        migrations.AlterField(
            model_name="author",
            name="last_name",
            field=models.CharField(max_length=50, verbose_name="Apellido"),
        ),
        migrations.AlterField(
            model_name="author",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="book",
            name="release",
            field=models.DateField(blank=True, null=True, verbose_name="Publicación"),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(max_length=30, verbose_name="Titulo"),
        ),
        migrations.AlterField(
            model_name="editorial",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Nombre"),
        ),
    ]
